default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails-vue-sandbox_development

test:
  <<: *default
  database: rails-vue-sandbox_test

production:
  <<: *default
  database: rails-vue-sandbox_production
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock
